In [2]:
import numpy as np                # library for array and matrix manipulation
import pprint                     # utilities for console printing 
import matplotlib.pyplot as plt   # visualization library

pp = pprint.PrettyPrinter(indent=4) # Instantiate a pretty printer

In [9]:
def make_basic_hashtable(value_list, n_bucket):

    def get_hash_value(value, n_bucket):
        return value % n_bucket

    hash_table = {i:[] for i in range(n_bucket)}
    for val in value_list:
        hash_value = get_hash_value(val, n_bucket)
        hash_table[hash_value].append(val)

    return hash_table

In [13]:
value_l = [100, 10, 14, 17, 97,76, 90, 76, 56, 44, 22 ,2, 262] # Set of values to hash
hash_table_example = make_basic_hashtable(value_l, 10)
hash_table_example

{0: [100, 10, 90],
 1: [],
 2: [22, 2, 262],
 3: [],
 4: [14, 44],
 5: [],
 6: [76, 76, 56],
 7: [17, 97],
 8: [],
 9: []}

In [14]:
P = np.array([[1, 1]])      # Single plane
v1 = np.array([[1, 2]])     # Sample point 1
v2 = np.array([[-1, 1]])    # Sample point 2
v3 = np.array([[-2, -1]])   # Sample point 3

In [36]:
def get_side_of_plane(p,v):
    dot = np.dot(p,v.T)
    sign = np.sign(dot)
    return sign

In [37]:
get_side_of_plane(P, v1) # In which side is [1, 2]

array([[1]])

In [38]:
P1 = np.array([[1, 1]])   # First plane 2D
P2 = np.array([[-1, 1]])  # Second plane 2D
P3 = np.array([[-1, -1]]) # Third plane 2D
P_l = [P1, P2, P3]  # List of arrays. It is the multi plane

# Vector to search
v = np.array([[2, 2]])

In [39]:
def get_combine_hash_value(p_l,v):
    hash_value = 0
    for i,p in enumerate(p_l):
        side = get_side_of_plane(p,v)
        ind_hash = 1 if side >-1 else 0
        hash_value += (2**i)*ind_hash
    return(hash_value)

In [40]:
get_combine_hash_value(P_l, v)

3

In [41]:
random_plane = np.random.normal(size=(3,2))
random_plane

array([[-0.27792741,  0.21962731],
       [ 0.28532774, -0.11798576],
       [-1.64074796, -0.05255411]])

In [42]:
v = np.array([[2,2]])

In [43]:
get_side_of_plane(random_plane,v)

array([[-1.],
       [ 1.],
       [-1.]])

In [46]:
def hash_multi_plane_matrix(P, v, num_planes):
    sides_matrix = get_side_of_plane(P, v) # Get the side of planes for P and v
    hash_value = 0
    for i in range(num_planes):
        sign = sides_matrix[i].item() # Get the value inside the matrix cell
        hash_i = 1 if sign >=0 else 0
        hash_value += 2**i * hash_i # sum 2^i * hash_i
        
    return hash_value

In [47]:
hash_multi_plane_matrix(random_plane, v, 3)

2

In [48]:
word_embedding = {"I": np.array([1,0,1]),
                   "love": np.array([-1,0,1]),
                   "learning": np.array([1,0,1])
                  }
words_in_document = ['I', 'love', 'learning', 'not_a_word']
document_embedding = np.array([0,0,0])
for word in words_in_document:
    document_embedding += word_embedding.get(word,0)
    
print(document_embedding)

[1 0 3]
