# C3W1

In [1]:
import tensorflow as tf

In [5]:
GRU_Model = tf.keras.Sequential([
    tf.keras.layers.GRU(256, return_sequences=True, name="GRU_1"),
    tf.keras.layers.GRU(128, return_sequences=True, name="GRU_2"),
    tf.keras.layers.GRU(64, return_sequences=True, name="GRU_3"),
    tf.keras.layers.Dense(10)
])

In [16]:
batch_size = 60 # no of batch
sequence_length = 50 # no fo words in array
word_vector_length = 40 #lvector ength of one word

input_data = tf.random.normal([batch_size,sequence_length,word_vector_length])
Prid = GRU_Model(input_data)

In [17]:
input_data[0][0]

<tf.Tensor: shape=(40,), dtype=float32, numpy=
array([-0.7715019 , -0.19145934,  2.0509696 , -0.23728472,  1.5857506 ,
       -0.82458645,  1.8611891 ,  0.6779198 ,  1.3143309 , -1.1583838 ,
       -0.50322783,  0.6190689 , -1.4922241 ,  1.012116  ,  0.5234752 ,
        0.7251767 ,  1.2710565 ,  0.46205455,  0.71745855, -0.29111665,
        0.3792743 ,  0.36056715,  0.33503586,  0.05311328, -1.138521  ,
        1.7453384 ,  0.42060208,  1.03028   , -1.7063988 ,  0.8396454 ,
        0.32447624,  0.45750624, -1.0561608 ,  1.0868046 ,  0.04485412,
        0.82398146,  1.0031745 ,  1.8075583 ,  0.5501563 ,  2.2163675 ],
      dtype=float32)>

In [10]:
GRU_Model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 GRU_1 (GRU)                 (60, 50, 256)             228864    
                                                                 
 GRU_2 (GRU)                 (60, 50, 128)             148224    
                                                                 
 GRU_3 (GRU)                 (60, 50, 64)              37248     
                                                                 
 dense_2 (Dense)             (60, 50, 10)              650       
                                                                 
Total params: 414,986
Trainable params: 414,986
Non-trainable params: 0
_________________________________________________________________


# Assignment?

In [2]:
import os
import traceback
import numpy as np
import random as rnd
import tensorflow as tf 
from tensorflow.keras import layers

In [3]:
# importing data 
file_path = "Assignment/data/shakespeare_data.txt"
lines = []
number_of_line = 0
with open(file_path,"r") as file:
    for line in file:
        pure_line = line.strip()
        if pure_line:
            lines.append(pure_line)
            number_of_line += 1

print(number_of_line," Lines found")
        

125097  Lines found


In [4]:
# viewing lines
print("\n".join(lines[2:10]))

A plaintful story from a sistering vale,
My spirits to attend this double voice accorded,
And down I laid to list the sad-tuned tale;
Ere long espied a fickle maid full pale,
Tearing of papers, breaking rings a-twain,
Storming her world with sorrow's wind and rain.
Upon her head a platted hive of straw,
Which fortified her visage from the sun,


In [5]:
# making vocabulary
text = "\n".join(lines)
vocab = sorted(set(text))
vocab.insert(0,'[UNK]')
vocab.insert(1,'')
print(len(vocab))
vocab

82


['[UNK]',
 '',
 '\t',
 '\n',
 ' ',
 '!',
 '$',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|']

In [6]:
# converting line into tensor 
eg_text = "Hellow World"
chars = tf.strings.unicode_split(eg_text, input_encoding='UTF-8')
print(chars)


tf.Tensor([b'H' b'e' b'l' b'l' b'o' b'w' b' ' b'W' b'o' b'r' b'l' b'd'], shape=(12,), dtype=string)


In [7]:
# now convertig the char into the numerical form 
eg_embeding = tf.keras.layers.StringLookup(vocabulary=list(vocab),mask_token=None)(chars)
eg_embeding

<tf.Tensor: shape=(12,), dtype=int64, numpy=array([34, 59, 66, 66, 69, 77,  4, 49, 69, 72, 66, 58], dtype=int64)>

In [8]:
# Now let's make the function to conver the line into tensor
def line_to_tensor(line,vocab):
    chars = tf.strings.unicode_split(line,input_encoding='UTF-8')
    embedding = tf.keras.layers.StringLookup(vocabulary=list(vocab),mask_token=None)(chars)
    return embedding

In [9]:
#testing the function
tmp_ids = line_to_tensor('abc xyz', vocab)
print(f"Result: {tmp_ids}")
print(f"Output type: {type(tmp_ids)}")
# tf.keras.layers.StringLookup(vocabulary=list(vocab), invert=True, mask_token= None)(tmp_ids)

Result: [55 56 57  4 78 79 80]
Output type: <class 'tensorflow.python.framework.ops.EagerTensor'>


In [10]:
# making reverse function i.e from embedding to text 
def tensor_to_line(tensor,vocab):
    char_from_ids= tf.keras.layers.StringLookup(vocabulary=list(vocab), invert=True, mask_token= None)
    line = tf.strings.reduce_join(char_from_ids(tensor))
    return line

In [11]:
# testing above function
print(tensor_to_line(tmp_ids,vocab))
tensor_to_line(tmp_ids,vocab).numpy()

tf.Tensor(b'abc xyz', shape=(), dtype=string)


b'abc xyz'

In [12]:
# preparing dataset
train_line = lines[:-1000]
eval_line = lines[-1000:]
print(len(train_line),len(eval_line),len(lines))

124097 1000 125097


In [13]:
all_ids = line_to_tensor("\n".join(["Hello world!", "Generative AI"]), vocab)
all_ids

<tf.Tensor: shape=(26,), dtype=int64, numpy=
array([34, 59, 66, 66, 69,  4, 77, 69, 72, 66, 58,  5,  3, 33, 59, 68, 59,
       72, 55, 74, 63, 76, 59,  4, 27, 35], dtype=int64)>

In [36]:
ids_dataset = tf.data.Dataset.from_tensor_slices(all_ids)
print([tensor_to_line([ids], vocab).numpy() for ids in ids_dataset.take(10)])

[b'H', b'e', b'l', b'l', b'o', b' ', b'w', b'o', b'r', b'l']


In [40]:
[i for i in ids_dataset.take(4)]

[<tf.Tensor: shape=(), dtype=int64, numpy=34>,
 <tf.Tensor: shape=(), dtype=int64, numpy=59>,
 <tf.Tensor: shape=(), dtype=int64, numpy=66>,
 <tf.Tensor: shape=(), dtype=int64, numpy=66>]

In [42]:
sequence_length = 10
data_generator = ids_dataset.batch(sequence_length+1,drop_remainder=True)
print([seq for seq in data_generator.take(2)])
print([tensor_to_line(seq,vocab) for seq in data_generator.take(2)],end="\n")

[<tf.Tensor: shape=(11,), dtype=int64, numpy=array([34, 59, 66, 66, 69,  4, 77, 69, 72, 66, 58], dtype=int64)>, <tf.Tensor: shape=(11,), dtype=int64, numpy=array([ 5,  3, 33, 59, 68, 59, 72, 55, 74, 63, 76], dtype=int64)>]
[<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world'>, <tf.Tensor: shape=(), dtype=string, numpy=b'!\nGenerativ'>]


In [43]:
def split_input_target(seq):
    input = seq[:-1]
    output = seq[1:]
    return input, output

In [44]:
split_input_target(list("Tensorflow"))

(['T', 'e', 'n', 's', 'o', 'r', 'f', 'l', 'o'],
 ['e', 'n', 's', 'o', 'r', 'f', 'l', 'o', 'w'])

In [66]:
def create_batch_dataset(lines, vocab, seq_length=100, batch_size=64):
    shuffler = 10000
    combile_line = "\n".join(lines)
    tensor_line = line_to_tensor(combile_line,vocab)
    id_dataset = tf.data.Dataset.from_tensor_slices(tensor_line)
    data_generator = id_dataset.batch(sequence_length+1,drop_remainder=True)
    data_inp_out = data_generator.map(split_input_target)

    dataset = (
        data_inp_out
        .shuffle(10000)
        .batch(batch_size, drop_remainder=True)
        .prefetch(tf.data.experimental.AUTOTUNE) 
    )
    return dataset

In [70]:
# test your function
dataset = create_batch_dataset(train_line[1:100], vocab, seq_length=16, batch_size=2)

print("Prints the elements into a single batch. The batch contains 2 elements: ")

for input_example, target_example in dataset.take(1):
    print("\n\033[94mInput0\t:", tensor_to_line(input_example[0], vocab).numpy())
    print("\n\033[93mTarget0\t:", tensor_to_line(target_example[0], vocab).numpy())
    
    print("\n\n\033[94mInput1\t:", tensor_to_line(input_example[1], vocab).numpy())
    print("\n\033[93mTarget1\t:", tensor_to_line(target_example[1], vocab).numpy())

Prints the elements into a single batch. The batch contains 2 elements: 

Input0	: b'r, being s'

Target0	: b', being sa'


Input1	: b"deified.\n'"

Target1	: b"eified.\n'H"


In [108]:
#creating dataset
batch_size = 64
dataset = create_batch_dataset(train_line,vocab,batch_size=batch_size,seq_length=100)

In [109]:
vocab_len = len(vocab)
embedding = 256
rnn_unit = 512
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_len,embedding),
    tf.keras.layers.GRU(rnn_unit,return_sequences=True),
    tf.keras.layers.Dense(vocab_len,activation=tf.nn.log_softmax)
])

In [110]:
model.build(input_shape=(batch_size,100))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, None, 256)         20992     
                                                                 
 gru_4 (GRU)                 (None, None, 512)         1182720   
                                                                 
 dense_4 (Dense)             (None, None, 82)          42066     
                                                                 
Total params: 1,245,778
Trainable params: 1,245,778
Non-trainable params: 0
_________________________________________________________________


In [115]:
for input, output in dataset.take(1):
    print(tensor_to_line(input[0],vocab))
    print(input[0])
    pridection = model(tf.constant([input[0].numpy()]))
    print(pridection.shape,"(batch_size, sequence_length, vocab_size)")
    print(vocab[np.argmax(pridection[0][-1].numpy())])
# model is prodecting anything 

tf.Tensor(b'tent,\nTo p', shape=(), dtype=string)
tf.Tensor([74 59 68 74 11  3 46 69  4 70], shape=(10,), dtype=int64)
(1, 10, 82) (batch_size, sequence_length, vocab_size)
o


In [118]:
# we have to train the model 
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer= tf.keras.optimizers.Adam(learning_rate=0.00125)
)

In [119]:
history = model.fit(
    dataset,
    epochs=10,
    verbose= True,
)

Epoch 1/10
7254/7254 [==============================] - 653s 90ms/step - loss: 1.7537
Epoch 2/10
7254/7254 [==============================] - 631s 87ms/step - loss: 1.6172
Epoch 3/10
7254/7254 [==============================] - 621s 86ms/step - loss: 1.5920
Epoch 4/10
7254/7254 [==============================] - 622s 86ms/step - loss: 1.5796
Epoch 5/10
7254/7254 [==============================] - 624s 86ms/step - loss: 1.5721
Epoch 6/10
7254/7254 [==============================] - 635s 88ms/step - loss: 1.5670
Epoch 7/10
7254/7254 [==============================] - 640s 88ms/step - loss: 1.5635
Epoch 8/10
7254/7254 [==============================] - 629s 87ms/step - loss: 1.5615
Epoch 9/10
7254/7254 [==============================] - 633s 87ms/step - loss: 1.5596
Epoch 10/10
7254/7254 [==============================] - 637s 88ms/step - loss: 1.5582


In [120]:
import shutil
output_dir = './model/'

try:
   shutil.rmtree(output_dir)
except OSError as e:
   pass

model.save_weights(output_dir)

In [136]:
def generate_one_word(inputs,states):
    tensor = line_to_tensor(inputs,vocab)
    pridected_ids,states = model(tensor,states,return_state=True)
    print(pridected_ids)
    word = tensor_to_line(pridected_ids,vocab)
    return word, states

In [137]:
prefix = "anuj"
num_chars = 10
states = None
next_char = tf.constant([prefix])
result = [next_char]
for n in range(num_chars):
    next_char, states = generate_one_word(next_char, states=states)
    result.append(next_char)

TypeError: Sequential.call() got an unexpected keyword argument 'return_state'